#!/bin/bash


if [ "$1" -le 0 ]
	then 
	 printf "Usage: uloha-linky NUMBER\nfor: 0<NUMBER\n"
	
	exit 1;
fi

ln /etc/hosts ./symLink1

for (( i=1; i<="$1"; i++ )) ;
	do
	tmp=$(( i+1 ))
	ln -s symLink$i symLink$tmp				
	done

exit 0;
